name: fitb_pantry_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  cloud_firestore: ^4.8.1
  email_validator: '^2.1.16'
  form_validator: ^2.1.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_svg: ^1.1.6
  firebase_core: ^2.4.0
  get: ^4.6.1
  l: ^4.0.1
  get_storage: ^2.0.3
  # BLoC
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2

  # Code generation for classes
  freezed: ^2.3.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  freezed_annotation:

  # Routing
  auto_route: ^7.8.3

  # HTTP requests
  dio: ^5.2.1+1

  # Native splash screen
  flutter_native_splash: ^2.3.1

  # Dependency Injection
  get_it: ^7.6.0
  analyzer: ^5.13.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  auto_route_generator: ^7.2.0

flutter_gen:
  output: lib/src/gen
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
    



flutter:
  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf  

